Verzeo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from skintone import views

urlpatterns = [
    path('', include('skintone.urls')),
    path('admin/', admin.site.urls),
] 

skintone/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static
from skintone import views

app_name = 'skin'
urlpatterns = [
    path('', views.home, name='home'),
    path('coding/', views.coding, name='coding'),
    path('readmore/', views.readmore, name='readmore'),
    path('robust/', views.robust, name='robust'),
    path('thankyou/', views.thankyou, name='thankyou'),
    path('preview/', views.preview, name='preview'),
    path('capture/', views.capture, name='capture'),
    path('preview/result/', views.result, name='result'),
    #path('imgprocess/', views.imgprocess, name='imgprocess')
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

skintone/models.py
from django.db import models
import numpy
from numpy.lib.type_check import imag
from . import views

# Create your models here.
from django.contrib.auth.models import User

from django.db.models.base import Model
from . import managers


class Fileupload(models.Model):
    fileupload = models.FileField()
    file_id = models.CharField(max_length=20,primary_key=True)
    objects=managers.fileuploaddetails_manager()

skintone/forms.py
# from django import forms
# class ImageUploadForm(forms.Form):
#     image= forms.ImageField()

skintone/views.py
# from skintone.forms import ImageUploadForm
from django.http import request
from django.shortcuts import redirect, render
# from .forms import ImageUploadForm
from django.views.decorators.csrf import csrf_exempt
from . import models
import os
import pprint
import sys
import cv2
import imutils
import numpy
from collections import Counter
from matplotlib import pyplot
from sklearn.cluster import KMeans
filees=""


# Create your views here.
def home(request):
    return render(request, 'skintone/home.html')


def coding(request):
    return render(request, 'skintone/coding.html')


def readmore(request):
    return render(request, 'skintone/readmore.html')


def robust(request):
    return render(request, 'skintone/robust.html')


def result(request):
    ans=imgprocess(filees)
    context={'ans':ans}
    return render(request, 'skintone/result.html', context)


def thankyou(request):
    return render(request, 'skintone/thankyou.html')

@csrf_exempt
def preview(request):
    print("Entere preview")
    if request.method== "POST":
        data= request.POST
        if data:
            print(data)
            if 'imagesubmit' in data:
                files = models.Fileupload.objects.filter(file_id='temp')
                fileupload = request.FILES.get('inputFile')
                if files.exists():
                    row = files[0]
                    row.fileupload = fileupload
                    row.save()

                else:
                    file_id ='temp'
                    fileupload = models.Fileupload.objects.create_fileupload(file_id=file_id,fileupload=fileupload)
                    fileupload.save() 
                    row = files[0]
                    row.fileupload = fileupload
                files = models.Fileupload.objects.filter(file_id='temp')
                if files.exists():
                    row = files[0]

                global filees
                filees = row.fileupload.name
                str(filees)
                print('type',type(filees))
                print(filees)
                imgprocess(filees)
    render(request, 'skintone/result.html' , {})
    return render(request, 'skintone/preview.html')


def capture(request):
    return render(request, 'skintone/capture.html')


def imgprocess(file):
    print('incoming',file)
    # Taking Input    
    detecter = FaceCropper()
    path = 'media/'+file
    print(path)
    (htap, galf) = detecter.generate( image_path = path, flag = 0)

    # (htap, galf) = detecter.generate(image_path = input("Image Address : "), flag = 0)

    # Cropped Image Doesn't Exist
    if galf == 4:
    
        print("No Face Detected!!!")
        print("Please Try Again!!!")
    
        # Cropped Image Exists
    if galf == 0:

        # Reading Cropped Image
        image = cv2.imread("CROP0.jpg")    
        os.remove("CROP0.jpg")

        # Apply Skin Mask
        skin = extractSkin(image)
        #skin = extractSkin(cv2.resize(image, (300, 300)))
        
        # Find the dominant color
        # Default is 1 , pass the parameter 'number_of_colors = N' where N is the specified number of colors
        # hasThresholding = True ignores black
        dominantColors = extractDominantColor(skin, number_of_colors = 4, hasThresholding = True)

        rgb_lower = [0, 0, 0]
        rgb_mid1 = [150, 95, 60]
        rgb_mid2 = [200, 172, 105]
        rgb_higher = [255, 255, 255]

        skin_shades = {'dark' : [rgb_lower, rgb_mid1], 'mild' : [rgb_mid1, rgb_mid2], 'fair' : [rgb_mid2, rgb_higher]}

        decimal_lower = rgb_lower[0] * 256 * 256 + rgb_lower[1] * 256 + rgb_lower[2]
        decimal_higher = rgb_higher[0] * 256 * 256 + rgb_higher[1] * 256 + rgb_higher[2]
        
        convert_skintones = {}
        
        for shade in skin_shades:
        
            convert_skintones.update(
                {
                    shade : 
                
                    [
                        skin_shades[shade][0][0] * 256 * 256 + skin_shades[shade][0][1] * 256 + skin_shades[shade][0][2],
                        skin_shades[shade][1][0] * 256 * 256 + skin_shades[shade][1][1] * 256 + skin_shades[shade][1][2]
                    ]
                }
            )

        unprocessed_dominant = extractDominantColor(skin, number_of_colors = 4, hasThresholding = True)
        dominantColors1 = []

        for clr in unprocessed_dominant:
        
            clr_decimal = 1 + int(clr['color'][0] * 256 * 256 + clr['color'][1] * 256 + clr['color'][2])
            
            if clr_decimal in range(decimal_lower, decimal_higher + 1):
            
                clr['decimal_color'] = clr_decimal
                dominantColors1.append(clr)

        skin_tones = []

        if len(dominantColors1) == 0:
        
            skin_tones.append('Unrecognized')
        
        else:
        
            for color in dominantColors1:
            
                for shade in convert_skintones:
                
                    if color['decimal_color'] in range(convert_skintones[shade][0], convert_skintones[shade][1] + 1):
                    
                        skin_tones.append(shade)

        #print(skin_tones)
        return skin_tones[0]



        #return redirect('thankyou')

class FaceCropper(object):

    # CASCADE_PATH = "data/haarcascades/haarcascade_frontalface_default.xml"
    CASCADE_PATH = "skintone/ML_Code/data/haarcascades/haarcascade_frontalface_default.xml"
    #CASCADE_PATH = "data/haarcascades/haarcascade_frontalface_alt.xml"
    #CASCADE_PATH = "data/haarcascades/haarcascade_frontalface_alt2.xml"
    #CASCADE_PATH = "data/lbpcascades/lbpcascade_frontalface.xml"
    #CASCADE_PATH = "data/lbpcascades/lbpcascade_frontalface_improved.xml"

    def __init__(self):

        self.face_cascade = cv2.CascadeClassifier(self.CASCADE_PATH)

    def generate(self, image_path, flag):

        img1 = cv2.imread(image_path)

        if (img1 is None):
            
            try:
                
                img2 = imutils.url_to_image(image_path)
                
            except:
                
                print()
                print("Image doesn't exist!!!")
                print("Please Try Again!!!")
                flag = 1
                return (image_path, flag)
            
            if (img2 is None):
                
                print()
                print("Image doesn't exist!!!")
                print("Please Try Again!!!")
                flag = 2
                return (image_path, flag)
            
            else:
                
                img = img2
        else:
            
            img = img1

        #img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        
        # Show Original Image
        
        # pyplot.figure(0)
        # pyplot.subplot(1, 3, 1)
        # pyplot.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
        # pyplot.title("Original Image")
        # pyplot.show()
        
        faces = self.face_cascade.detectMultiScale(img, 1.1, 6)#, minSize = (100, 100))

        if (faces is None):
            
            print()
            print("No Face detected")
            print("Please Try Again!!!")
            flag = 3
            return (image_path, flag)
        
        for (x, y, w, h) in faces:
            
            cv2.rectangle(img, (x, y), (x+w, y+h), (255, 225, 225), 1)
            #break
        
        cv2.imshow('img', img)
        cv2.waitKey(1)
        cv2.destroyAllWindows()

        facecount = len(faces)
        #print("Detected faces: %d" % facecount)
        if facecount == 0:
            
            flag = 4
            return (image_path, flag)
        
        #height, width = img.shape[:2]
        
        i = 0

        for (x, y, w, h) in faces:

            r = max(w, h) / 2
            centerx = x + w / 2
            centery = y + h / 2
            nx = int(centerx - r)
            ny = int(centery - r)
            nr = int(r * 2)

            #faceimg = img[ny:ny+nr, nx:nx+nr]
            #lastimg = cv2.resize(faceimg, (300, 300))
            lastimg = img[ny:ny+nr, nx:nx+nr]
            #image = imutils.resize(image, width = 300)
            
            cv2.imwrite("CROP%d.jpg" %i, lastimg)
            i += 1
            #break
        
        flag = 0
        return (image_path, flag)


def extractSkin(image):

    # Taking a copy of the image
    img = image.copy()

    # Converting from BGR Colours Space to HSV
    img = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)

    # Defining HSV Threadholds
    lower_threshold = numpy.array([0, 48, 80], dtype = numpy.uint8)
    
    upper_threshold = numpy.array([20, 255, 255], dtype = numpy.uint8)

    # Single Channel mask, denoting presence of colours in the about threshold
    skinMask = cv2.inRange(img, lower_threshold, upper_threshold)

    # Cleaning up mask using Gaussian Filter
    skinMask = cv2.GaussianBlur(skinMask, (3, 3), 0)

    # Extracting skin from the threshold mask
    skin = cv2.bitwise_and(img, img, mask = skinMask)

    # Return the Skin image
    return cv2.cvtColor(skin, cv2.COLOR_HSV2BGR)


def removeBlack(estimator_labels, estimator_cluster):

    # Check for black
    hasBlack = False

    # Get the total number of occurences for each color
    occurance_counter = Counter(estimator_labels)

    # Quick lambda function to compare to lists
    def compare(x, y): 
        return Counter(x) == Counter(y)

    # Loop through the most commonly occuring color
    for x in occurance_counter.most_common(len(estimator_cluster)):

        # Quick List comprehension to convert each of RBG Numbers to int
        color = [int(i) for i in estimator_cluster[x[0]].tolist()]

        # Check if the color is [0, 0, 0]/[1, 0, 0] that if it is black
        if compare(color, [0, 0, 0]) == True or compare(color, [1, 0, 0]) == True:
            
            # Delete the occurence
            del occurance_counter[x[0]]
            
            # Remove the cluster

skintone/templates/skintone/capture.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detect Skin</title>
    <script src="https://kit.fontawesome.com/f2d84446ed.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'skintone/home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'skintone/preview/css/styles.css' %}" />
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet"/>

    <link rel="stylesheet" href="{% static 'skintone/preview/css/capture.css' %}">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'skin:home' %}"><p id="logo">DETECT SKIN</p></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'skin:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'skin:preview' %}">Preview</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'skin:home' %}#contact">Contact Us </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <header class="page-header gradient">
      <div class="container pt-3">
        <div class="row  justify-content-center">
            <div class="container">
              <br>
              <div>
                <div class= "video1">
                <h2>Live Camera :</h2>
                  <video id="player" controls autoplay width="320" height="240"></video><br>
                    <input type="button" name="inputFile" id="capture" value="Capture"><br>
                  </div>
                  <div class= "canvas1">
                    <h2>Captured Image :</h2>
                    <canvas id="canvas" width=320 height=240></canvas><br><br><br><br><br><br>
                    </div><br><br><br><br><br><br><br><br><br><br><br><br><br>
                    <h4>
                      <ul>INSTRUCTIONS</ul>
                    <li>Step 1: Right click on Captured image</li>
                    <li>Step 2: Save it in your Device</li>
                    <li>Step 3: Go back to the preview page</li>
                    <li>Step 4: Upload the saved image</li>
                  </h4>
                  </h4><br><br>
                    <h2>" Any Problem ? We Can Help You ! "</h2><br>
                    <section id="contact" class="contact">
                      <div class="container">
                        <div class="row">
                          <div class="col-md-5">
                            <h1 style="font-weight: 800;">Contact us:</h1>
                            <div class="mb-3">
                              <label for="exampleFormControlInput1" class="form-label"
                                >Email address</label
                              >
                              <input
                                type="email"
                                class="form-control"
                                id="exampleFormControlInput1"
                                placeholder="name@example.com"
                              />
                            </div>
                            <div class="mb-3">
                              <label for="exampleFormControlTextarea1" class="form-label"
                                >Message: </label
                              >
                              <textarea
                                class="form-control"
                                id="exampleFormControlTextarea1"
                                rows="3"
                              ></textarea>
                            </div>
                            <form>
                            <a href="{% url 'skin:thankyou' %}" class="btn btn-outline-warning">Send</a>
                          </form>
                            <br>
                          </div>
                          <div class="col-md-6">
                            <img src="{% static 'skintone/preview/img/handshake.svg' %}" alt="Contact image" />
                          </div>
                        </div>
                      </div>
                    </section>
                  </header>
                  <script>
                     const player = document.getElementById('player');
                     const canvas = document.getElementById('canvas');
                     const context = canvas.getContext('2d');
                     const captureButton = document.getElementById('capture');
          
                     const constraints = {
                         video: true,
                        };
          
                     captureButton.addEventListener('click', () => {
                       // Draw the video frame to the canvas.
                     context.drawImage(player, 0, 0, canvas.width, canvas.height);
                         });


                      
                         
          
                         // Attach the video stream to the video element and autoplay.
                      navigator.mediaDevices.getUserMedia(constraints)
                         .then((stream) => {
                            player.srcObject = stream;
                           });
                   </script>
               </div>
            </div>
    <footer class="gradient">
      <div class="container-fluid text-center">
        <span
          >Submitted By:
          <a class="grp" href="#">Human Skintone Group B8</a></span
        >
      </div>
    </footer>
    <script src="{% static 'skintone/home/js/bootstrap.min.js' %}"></script>
  </body>
  <style>
    a.grp:hover {color: yellow;}
    .btn-grid
{
    margin: -2px 0;
}

.btn-grid > .btn
{
    margin: 2px 0;
}
h4{
    margin-left: 10%;
    color: rgb(255, 255, 255);
    padding-top: 88px;
    font-family: Segoe UI, Tahoma, Geneva,'Verdana', sans-serif;
    font-size: 200%;
}
  </style>
</html>

skintone/templates/skintone/preview.html
{% load static %}
<!DOCTYPE >
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href="{% static 'skintone/preview/css/preview.css' %}" />
    <link rel="stylesheet" media="screen" href="https://fontlibrary.org//face/mayin-s-hand" type="text/css"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detect Skin</title>
    <script src="https://kit.fontawesome.com/f2d84446ed.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'skintone/home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'skintone/preview/css/styles.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'skin:home' %}"><p id="logo">DETECT SKIN</p></a>
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbarNav"
        aria-controls="navbarNav"
        aria-expanded="false"
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div
        class="collapse navbar-collapse justify-content-end"
        id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'skin:home' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="#preview">Preview</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'skin:home' %}">Contact Us </a>
          </li>
        </ul>
      </div>
    </div>
  </nav>          
  <header class="page-header gradient">
    <div class="container pt-3">
        <div class="row  justify-content-center">
          <div class="container">
            <h3>Welcome To Our Studio!</h3> 
            <h1> KNOW YOUR SKIN TONE </h1><br>
            
            <div class="model">
              <img src="{% static 'skintone/home/img/email_campaign_monochromatic.svg' %}" alt="Header image">
            </div>
              <h4>
                <ul>SPECIFICATIONS</ul>
              <li>Recognize skin tone efficiently</li>
              <li>Built with Latest Technology</li>
              <li>Super Responsive</li>
              <li>Accurate results</li>
            </h4>
            </h4>
            <br><br>
            <form autocomplete="off"  method="POST" name="fileuploadform" enctype="multipart/form-data">
              
              <div class="form-group inputDnD">
                  <input type="file" name="inputFile" class="form-control-file text-primary font-weight-bold" id="inputFile" accept="image/*" >
                </div> 
                <a id="one" class="btn btn-warning" href="{% url 'skin:capture' %}">CAPTURE-IMAGE</a>
                <a id="six"  class="btn btn-warning" onclick="document.getElementById('inputFile').click()">UPLOAD-FILE</a>
                <input type="submit"  name="imagesubmit" class ="btn btn-success" value="submit">
                <div class="image-preview" id="imagePreview">
                  <img src="" alt="Image Preview" class="image-preview__image">
                  <span class="image-preview__default-text">Image Preview</span>
                </div>
                <br><br>
                   <a id="five" class="btn btn-success" href='result'>Check Result</a>
              </div>
            </form>  
            </div>
            </div>
            </div>
            </div>
            <br>
            <footer class="gradient">
              <div class="container-fluid text-center">
                <span
                  >Submitted By:
                  <a class="grp" href="#">Human Skintone Group B8</a></span
                >
              </div>
            </footer>
            <script>
              const inpFile = document.getElementById("inputFile");
              const previewContainer = document.getElementById("imagePreview");
              const previewImage = previewContainer.querySelector(".image-preview__image");
              const previewDefaultText = previewContainer.querySelector(".image-preview__default-text");

              inputFile.addEventListener("change", function() {
                const file = this.files[0];
                if (file) {
                  const reader = new FileReader();

                  previewDefaultText.style.display = "none";
                  previewImage.style.display = "block";

                  reader.addEventListener("load", function() {
                    console.log(this);
                    previewImage.setAttribute("src", this.result);
                  });
                  reader.readAsDataURL(file);
                }

              });

            </script>
            <script src="{% static 'skintone/home/js/bootstrap.min.js' %}"></script>
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
</body>
<style>
  a.grp:hover {color: yellow;}
  .btn-grid
{
  margin: -2px 0;
}

.btn-grid > .btn
{
  margin: 2px 0;
}
</style>
</html>

skintone/templates/skintone/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Detectskin</title>
    <script src="https://kit.fontawesome.com/f2d84446ed.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'skintone/home/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'skintone/home/css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'skintone/result/css/result.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200&family=Ubuntu:wght@300&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'skin:home' %}"><p id="logo">detect-skin</p></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNav"
          aria-controls="navbarNav"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div
          class="collapse navbar-collapse justify-content-end"
          id="navbarNav"
        >
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'skin:home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'skin:home' %}">Services</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'skin:readmore' %}">Read More</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'skin:home' %}">Contact Us </a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <header class="page-header gradient">
      <div class="container pt-3">
        <div class="row align-items-center justify-content-center">
              <br><br><br><br><br><br>
            <div class="model">
              <img src="{% static 'skintone/home/img/marketing.svg' %}" alt="Header image">
            </div>
            <h2>Your SkinTone is :{{ ans }}</h2>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
            </div>
            </div>
            </header>
          

    <footer class="gradient">
      <div class="container-fluid text-center">
        <span
          >Submitted By:
          <a class="grp" href="#">Human Skintone Group B8</a></span
        >
      </div>
    </footer>
    <script>
        const inpFile = document.getElementById("inputFile");
        const previewContainer = document.getElementById("imagePreview");
        const previewImage = previewContainer.querySelector(".image-preview__image");
        const previewDefaultText = previewContainer.querySelector(".image-preview__default-text");

        inputFile.addEventListener("change", function() {
          const file = this.files[0];
          if (file) {
            const reader = new FileReader();

            previewDefaultText.style.display = "none";
            previewImage.style.display = "block";

            reader.addEventListener("load", function() {
              console.log(this);
              previewImage.setAttribute("src", this.result);
            });
            reader.readAsDataURL(file);
          }

        });
        </script>
    <script src="{% static 'skintone/home/js/bootstrap.min.js' %}"></script>
  </body>
  <style>
    a.grp:hover {color: yellow;}
    .btn-grid
{
    margin: -2px 0;
}

.btn-grid > .btn
{
    margin: 2px 0;
}
  </style>
  
</html>